# Generated by Django 3.1.3 on 2020-12-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.IntegerField(max_length=12, null=True)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
